# Generated by Django 3.2.13 on 2022-06-09 20:53

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_country_state'),
        ('course_metadata', '0282_remove_uniqueness_on_program_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Only relevant when country is set to "US".', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.country'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='state',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Only relevant when country is set to "US".', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.state'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.country'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='state',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Only relevant when country is set to "US".', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.state'),
        ),
        migrations.AddField(
            model_name='program',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
        migrations.AddField(
            model_name='program',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Only relevant when country is set to "US".', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state'),
        ),
        migrations.CreateModel(
            name='ProgramLocationRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('allowlist', 'Allowlist'), ('blocklist', 'Blocklist')], default='allowlist', max_length=255)),
                ('countries', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='course_metadata_programlocationrestriction_country', related_query_name='course_metadata_programlocationrestrictions', to='core.Country')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_metadata.program')),
                ('states', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='course_metadata_programlocationrestriction_state', related_query_name='course_metadata_programlocationrestrictions', to='core.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseLocationRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('allowlist', 'Allowlist'), ('blocklist', 'Blocklist')], default='allowlist', max_length=255)),
                ('countries', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='course_metadata_courselocationrestriction_country', related_query_name='course_metadata_courselocationrestrictions', to='core.Country')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_metadata.course')),
                ('states', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='course_metadata_courselocationrestriction_state', related_query_name='course_metadata_courselocationrestrictions', to='core.State')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
